Fix brew install warning
An error was printed when called `brew install swiftlint.rb`. It turned out brew has now `install --formula` parameter which allows to install from local formula file.

```bash
...
Error: Failed to load cask: swiftlint.rb
Cask 'swiftlint' is unreadable: wrong constant name #<Class:0x000000013f213780>
Warning: Treating swiftlint.rb as a formula.
...
```

Test Plan:
- Ensure all CI checks pass
- Inspect CI logs, ensure no error or warning is reported

Signed-off-by: Marcin Iwanicki <miwanicki1@bloomberg.net>